services:
  erp-asy-syifaa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: erp-asy-syifaa
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./backend/data:/app/backend/data
      - ./backend/storage/library-pdfs:/app/backend/storage/library-pdfs
    environment:
      - PORT=3000
